# Hand-written stub, sibling to the auto-generated `_gamestate/__init__.pyi`.
#
# `_gamestate/__init__.pyi` is regenerated by `cargo run --bin stub_gen`
# (wired into the `rust-stub-gen` pre-commit hook) and only describes the
# Rust-native `GameState` shape. It has no idea about the `StateBuilders`
# methods that get monkey-patched onto `GameState` at import time in
# `gamestate/__init__.py` (see `gamestate/gamestate/builders.py`), nor about
# the extra query methods added there. This file fills that gap for
# pyrefly / other type checkers. Do NOT edit `_gamestate/__init__.pyi` by
# hand -- it gets overwritten. Do edit this file when `builders.py`'s public
# surface changes.

from typing import Any, Literal

from petty._petty import SlotData

# NOTE: deliberately not `from ._gamestate import *` -- wildcard-importing
# `GameState` here and then redefining it below via `class GameState(...)`
# confuses pyrefly's constructor-call resolution (it ends up treating
# `GameState()` as returning the original `_gamestate.GameState` in some
# contexts instead of this subclass). Importing everything else by name and
# aliasing `GameState` avoids the ambiguous double-binding.
from ._gamestate import (
    AttributeModifier as AttributeModifier,
)
from ._gamestate import (
    BlockEntity as BlockEntity,
)
from ._gamestate import (
    CombatEventType as CombatEventType,
)
from ._gamestate import (
    Difficulty as Difficulty,
)
from ._gamestate import (
    Dimension as Dimension,
)
from ._gamestate import (
    Entity as Entity,
)
from ._gamestate import (
    EntityAttribute as EntityAttribute,
)
from ._gamestate import (
    EntityEffect as EntityEffect,
)
from ._gamestate import (
    EntityEquipment as EntityEquipment,
)
from ._gamestate import (
    EntityFlags as EntityFlags,
)
from ._gamestate import (
    EntityStatus as EntityStatus,
)
from ._gamestate import (
    EquipmentSlot as EquipmentSlot,
)
from ._gamestate import (
    Gamemode as Gamemode,
)
from ._gamestate import GameState as _RustGameState
from ._gamestate import (
    GameStateReason as GameStateReason,
)
from ._gamestate import (
    MapData as MapData,
)
from ._gamestate import (
    MetadataValue as MetadataValue,
)
from ._gamestate import (
    Player as Player,
)
from ._gamestate import (
    PlayerAbilityFlags as PlayerAbilityFlags,
)
from ._gamestate import (
    PlayerInfo as PlayerInfo,
)
from ._gamestate import (
    PlayerListAction as PlayerListAction,
)
from ._gamestate import (
    PluginChannel as PluginChannel,
)
from ._gamestate import (
    ResourcePack as ResourcePack,
)
from ._gamestate import (
    Rotation as Rotation,
)
from ._gamestate import (
    Score as Score,
)
from ._gamestate import (
    ScoreboardObjective as ScoreboardObjective,
)
from ._gamestate import (
    Statistics as Statistics,
)
from ._gamestate import (
    Team as Team,
)
from ._gamestate import (
    TeamMode as TeamMode,
)
from ._gamestate import (
    TitleAction as TitleAction,
)
from ._gamestate import (
    TitleState as TitleState,
)
from ._gamestate import (
    Vec3d as Vec3d,
)
from ._gamestate import (
    Vec3i as Vec3i,
)
from ._gamestate import (
    VillagerTrade as VillagerTrade,
)
from ._gamestate import (
    Window as Window,
)
from ._gamestate import (
    WorldBorder as WorldBorder,
)
from ._gamestate import (
    WorldBorderAction as WorldBorderAction,
)

# (packet_id, packet_data) tuple returned by the packet-building helpers.
type Packet = tuple[int, bytes]

class GameState(_RustGameState):  # type: ignore[invalid-inheritance]
    # At runtime there is no actual subclass -- `builders.py`'s methods are
    # monkey-patched directly onto the Rust `GameState` class via `setattr`,
    # so `gamestate.GameState is gamestate._gamestate.GameState`. This stub
    # subclass exists purely so type checkers see the merged interface.
    # `_RustGameState.__new__` is typed to return the literal `_gamestate.
    # GameState` type, not `Self`, so without this override callers doing
    # `x: GameState = GameState()` would see a type mismatch.
    def __new__(cls) -> GameState: ...

    # --- packet builders (StateBuilders, monkey-patched in __init__.py) ---
    def _build_join_game(
        self, eid: int | None = ..., gamemode: Literal[1, 2, 3, 4] | None = ...
    ) -> Packet: ...
    def _build_server_difficulty(self) -> Packet: ...
    def _build_player_abilities(self) -> Packet: ...
    def _build_held_item_change(self) -> Packet: ...
    def _build_spawn_position(self) -> Packet: ...
    def _build_player_position_and_look(self) -> Packet: ...
    def _build_update_health(self) -> Packet: ...
    def _build_set_experience(self) -> Packet: ...
    def _build_time_update(self) -> Packet: ...
    def _build_world_border(self) -> Packet: ...
    def _build_player_list_items(self) -> list[Packet]: ...
    def _build_player_list_header_footer(self) -> Packet: ...
    def _build_scoreboard_objectives(self) -> list[Packet]: ...
    def _build_scoreboard_scores(self) -> list[Packet]: ...
    def _build_display_scoreboards(self) -> list[Packet]: ...
    def _build_teams(self) -> list[Packet]: ...
    def _build_chunk_data(self) -> list[Packet]: ...
    def _build_block_entities(self) -> list[Packet]: ...
    def _build_entity_spawns(self) -> list[Packet]: ...
    def _build_spawn_player(self, player: Player) -> Packet: ...
    def build_entity_teleports(self) -> list[Packet]: ...
    def _build_npc_player_spawns(self) -> list[Packet]: ...
    def _build_npc_removal_packet(self) -> Packet: ...
    def _build_spawn_mob(self, entity: Entity) -> Packet: ...
    def _build_spawn_object(self, entity: Entity) -> Packet: ...
    def _build_entity_metadata(self) -> list[Packet]: ...
    def _build_entity_equipment(self) -> list[Packet]: ...
    def _build_entity_effects(self) -> list[Packet]: ...
    def _build_entity_properties(self) -> list[Packet]: ...
    def _build_player_inventory(self) -> Packet: ...
    def _build_open_window(self) -> list[Packet]: ...
    def _build_statistics(self) -> Packet: ...
    def _build_title(self) -> list[Packet]: ...
    def _build_game_state_changes(self) -> list[Packet]: ...
    def _build_maps(self) -> list[Packet]: ...
    def _build_resource_pack(self) -> Packet: ...
    def _build_camera(self) -> Packet: ...
    def _build_block_break_animations(self) -> list[Packet]: ...
    def _pack_uuid(self, uuid_str: str) -> bytes: ...
    def _pack_metadata(self, metadata: dict[int, MetadataValue | Any]) -> bytes: ...
    def send_update(self) -> list[Packet]: ...
    def sync_spectator(self, eid: int | None = ...) -> list[Packet]: ...
    def sync_broadcast_spectator(self, eid: int) -> list[Packet]: ...

    # --- query helpers (StateBuilders, monkey-patched in __init__.py) ---
    def get_entity(self, entity_id: int) -> Entity | None: ...
    def get_player_by_uuid(self, uuid: str) -> Player | None: ...
    def get_player_by_name_from_player_list(self, name: str) -> PlayerInfo | None: ...
    def real_players(self) -> set[str]: ...
    def get_held_item(self) -> SlotData | None: ...
    def get_armor(self) -> list[SlotData | None]: ...
    @property
    def health(self) -> float: ...
