"""this is not even close the best way to do this lmao but whatever"""

import abc
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass
from io import BytesIO
from typing import Any, Literal, Protocol, TypedDict, overload

from _typeshed import Incomplete

class AsyncReader[T](Protocol):
    async def read(self, n: int = -1) -> T: ...

type Color_T = Literal[
    "black",
    "dark_blue",
    "dark_green",
    "dark_aqua",
    "dark_red",
    "dark_purple",
    "gold",
    "gray",
    "dark_gray",
    "blue",
    "green",
    "aqua",
    "red",
    "light_purple",
    "yellow",
    "white",
]

@dataclass
class Pos:
    x: int = ...
    y: int = ...
    z: int = ...

class ItemDict(TypedDict):
    id: int
    name: str
    display_name: str
    data: int

item_mapping: list[ItemDict]

class Item:
    id: ItemID
    name: ItemName
    display_name: DisplayName
    data: int = 0

    @classmethod
    def from_name(cls, name: ItemName) -> Item:
        """Create an Item instance from a name."""

    @classmethod
    def from_display_name(cls, display_name: DisplayName) -> Item:
        """Create an Item instance from a display name."""

    @classmethod
    def from_id(cls, id: ItemID) -> Item:
        """Create an Item instance from an ID."""

class SlotData:
    item: Item | None
    count: int
    damage: int
    nbt: bytes
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self, item: Item, count: int = ..., damage: int = ..., nbt: bytes = ...
    ) -> None: ...

class Buffer(BytesIO):
    def unpack[T](self, kind: type[DataType[Any, T]]) -> T: ...
    def clone(self) -> Buffer: ...

class MapData(TypedDict):
    max_height: int | None
    min_height: int | None
    rush_direction: Literal["side", "alt"]

BW_MAPS = dict[str, MapData]

class DataType[PT, UT](ABC, metaclass=abc.ABCMeta):
    value: PT | UT
    def __new__(cls, value: PT) -> bytes: ...
    @staticmethod
    @abstractmethod
    def pack(value: PT) -> bytes: ...
    @staticmethod
    @abstractmethod
    def unpack(buff: Buffer) -> UT: ...

class VarInt(DataType[int, int]):
    @staticmethod
    def pack(value: int) -> bytes: ...
    @staticmethod
    def unpack(buff) -> int: ...
    @staticmethod
    async def unpack_stream(stream: AsyncReader[bytes]) -> int: ...

class UnsignedShort(DataType[int, int]):
    @staticmethod
    def pack(value: int) -> bytes: ...
    @staticmethod
    def unpack(buff) -> int: ...

class Short(DataType[int, int]):
    @staticmethod
    def pack(value: int) -> bytes: ...
    @staticmethod
    def unpack(buff) -> int: ...

class Long(DataType[int, int]):
    @staticmethod
    def pack(value: int) -> bytes: ...
    @staticmethod
    def unpack(buff) -> int: ...

class Byte(DataType[bytes | int | float, int]):
    @staticmethod
    def pack(value: bytes | int | float) -> bytes: ...
    @staticmethod
    def unpack(buff) -> int: ...

class UnsignedByte(DataType[int, int]):
    @staticmethod
    def pack(value: bytes | int | float) -> bytes: ...
    @staticmethod
    def unpack(buff) -> int: ...

class ByteArray(DataType[bytes, bytes]):
    @staticmethod
    def pack(value: bytes) -> bytes: ...
    @staticmethod
    def unpack(buff) -> bytes: ...

class TextComponent:
    COLOR_CODES: Incomplete
    FORMAT_CODES: Incomplete
    data: dict
    def __init__(self, data=None) -> None: ...
    def set_text(self, text: str) -> TextComponent: ...
    def set_translate(
        self, key: str, with_args=None, fallback=None
    ) -> TextComponent: ...
    def set_score(self, name: str, objective: str) -> TextComponent: ...
    def set_selector(self, selector: str, separator=None) -> TextComponent: ...
    def set_keybind(self, keybind: str) -> TextComponent: ...
    def set_nbt(
        self,
        nbt_path: str,
        source: str | None = None,
        block: str | None = None,
        entity: str | None = None,
        storage: str | None = None,
        interpret: bool = False,
        separator=None,
    ) -> TextComponent: ...
    def color(
        self,
        color: Color_T,
    ) -> TextComponent: ...
    def font(self, font: str) -> TextComponent: ...
    def bold(self, bold: bool = True) -> TextComponent: ...
    def italic(self, italic: bool = True) -> TextComponent: ...
    def underlined(self, underlined: bool = True) -> TextComponent: ...
    def strikethrough(self, strikethrough: bool = True) -> TextComponent: ...
    def obfuscated(self, obfuscated: bool = True) -> TextComponent: ...
    def shadow_color(self, color) -> TextComponent: ...
    def insertion(self, text: str) -> TextComponent: ...
    def click_event(
        self,
        action: Literal[
            "open_url",
            "run_command",
            "suggest_command",
            "change_page",
            # "copy_to_clipboard", # does not seem to work in 1.8
        ],
        value: str,
    ) -> TextComponent: ...
    def hover_text(self, text) -> TextComponent: ...
    def append(self, component) -> TextComponent: ...
    def appends(self, component, separator: str = " ") -> TextComponent: ...
    def extend(self, components) -> TextComponent: ...
    def prepend(self, component) -> TextComponent: ...
    def remove_child(self, index: int) -> TextComponent: ...
    def replace_child(self, index: int, component) -> TextComponent: ...
    def clear_children(self) -> TextComponent: ...
    def copy(self) -> TextComponent: ...
    def to_dict(self) -> dict: ...
    def to_json(self) -> str: ...
    def is_empty(self) -> bool: ...
    def get_children(self) -> list[TextComponent]: ...
    def flatten(self) -> TextComponent: ...
    def to_legacy(self) -> str: ...
    @classmethod
    def from_legacy(cls, text: str) -> TextComponent: ...

class Chat(DataType[str, str]):
    @staticmethod
    def pack(value: str | TextComponent | dict) -> bytes: ...
    @staticmethod
    def pack_msg(value: str | TextComponent | dict) -> bytes: ...
    @staticmethod
    def unpack(buff) -> str: ...
    @staticmethod
    def unpack_component(buff) -> TextComponent: ...

class String(DataType[str | TextComponent, str]):
    @staticmethod
    def pack(value: str | TextComponent) -> bytes: ...
    @staticmethod
    def unpack(buff) -> str: ...

class UUID(DataType[uuid.UUID, uuid.UUID]):
    @staticmethod
    def pack(value: uuid.UUID) -> bytes: ...
    @staticmethod
    def unpack(buff) -> uuid.UUID: ...

class Boolean(DataType[bool, bool]):
    @staticmethod
    def pack(value: bool) -> bytes: ...
    @staticmethod
    def unpack(buff) -> bool: ...

class Int(DataType[int, int]):
    @staticmethod
    def pack(value: int) -> bytes: ...
    @staticmethod
    def unpack(buff) -> int: ...

class Position(DataType[Pos, Pos]):
    @staticmethod
    def pack(value: tuple[int, int, int] | Pos) -> bytes: ...
    @staticmethod
    def unpack(buff) -> Pos: ...

class Double(DataType[float, float]):
    @staticmethod
    def pack(value: float) -> bytes: ...
    @staticmethod
    def unpack(buff) -> float: ...

class Float(DataType[float, float]):
    @staticmethod
    def pack(value: float) -> bytes: ...
    @staticmethod
    def unpack(buff) -> float: ...

class Angle(DataType[float, float]):
    @staticmethod
    def pack(value: float) -> bytes: ...
    @staticmethod
    def unpack(buff: Buffer) -> float: ...

class Slot(DataType[SlotData, SlotData]):
    @staticmethod
    def pack(value: SlotData) -> bytes: ...
    @staticmethod
    def unpack(buff: Buffer) -> SlotData: ...

# Auto-generated from ./assets/item_mappings.json
type ItemName = Literal[
    "minecraft:acacia_door",
    "minecraft:acacia_fence",
    "minecraft:acacia_fence_gate",
    "minecraft:acacia_stairs",
    "minecraft:activator_rail",
    "minecraft:air",
    "minecraft:anvil",
    "minecraft:apple",
    "minecraft:armor_stand",
    "minecraft:arrow",
    "minecraft:baked_potato",
    "minecraft:banner",
    "minecraft:barrier",
    "minecraft:beacon",
    "minecraft:bed",
    "minecraft:bedrock",
    "minecraft:beef",
    "minecraft:birch_door",
    "minecraft:birch_fence",
    "minecraft:birch_fence_gate",
    "minecraft:birch_stairs",
    "minecraft:blaze_powder",
    "minecraft:blaze_rod",
    "minecraft:boat",
    "minecraft:bone",
    "minecraft:book",
    "minecraft:bookshelf",
    "minecraft:bow",
    "minecraft:bowl",
    "minecraft:bread",
    "minecraft:brewing_stand",
    "minecraft:brick",
    "minecraft:brick_block",
    "minecraft:brick_stairs",
    "minecraft:brown_mushroom",
    "minecraft:brown_mushroom_block",
    "minecraft:bucket",
    "minecraft:cactus",
    "minecraft:cake",
    "minecraft:carpet",
    "minecraft:carrot",
    "minecraft:carrot_on_a_stick",
    "minecraft:cauldron",
    "minecraft:chainmail_boots",
    "minecraft:chainmail_chestplate",
    "minecraft:chainmail_helmet",
    "minecraft:chainmail_leggings",
    "minecraft:chest",
    "minecraft:chest_minecart",
    "minecraft:chicken",
    "minecraft:clay",
    "minecraft:clay_ball",
    "minecraft:clock",
    "minecraft:coal",
    "minecraft:coal_block",
    "minecraft:coal_ore",
    "minecraft:cobblestone",
    "minecraft:cobblestone_wall",
    "minecraft:command_block",
    "minecraft:command_block_minecart",
    "minecraft:comparator",
    "minecraft:compass",
    "minecraft:cooked_beef",
    "minecraft:cooked_chicken",
    "minecraft:cooked_fish",
    "minecraft:cooked_mutton",
    "minecraft:cooked_porkchop",
    "minecraft:cooked_rabbit",
    "minecraft:cookie",
    "minecraft:crafting_table",
    "minecraft:dark_oak_door",
    "minecraft:dark_oak_fence",
    "minecraft:dark_oak_fence_gate",
    "minecraft:dark_oak_stairs",
    "minecraft:daylight_detector",
    "minecraft:deadbush",
    "minecraft:detector_rail",
    "minecraft:diamond",
    "minecraft:diamond_axe",
    "minecraft:diamond_block",
    "minecraft:diamond_boots",
    "minecraft:diamond_chestplate",
    "minecraft:diamond_helmet",
    "minecraft:diamond_hoe",
    "minecraft:diamond_horse_armor",
    "minecraft:diamond_leggings",
    "minecraft:diamond_ore",
    "minecraft:diamond_pickaxe",
    "minecraft:diamond_shovel",
    "minecraft:diamond_sword",
    "minecraft:dirt",
    "minecraft:dispenser",
    "minecraft:double_plant",
    "minecraft:dragon_egg",
    "minecraft:dropper",
    "minecraft:dye",
    "minecraft:egg",
    "minecraft:emerald",
    "minecraft:emerald_block",
    "minecraft:emerald_ore",
    "minecraft:enchanted_book",
    "minecraft:enchanting_table",
    "minecraft:end_portal_frame",
    "minecraft:end_stone",
    "minecraft:ender_chest",
    "minecraft:ender_eye",
    "minecraft:ender_pearl",
    "minecraft:experience_bottle",
    "minecraft:farmland",
    "minecraft:feather",
    "minecraft:fence",
    "minecraft:fence_gate",
    "minecraft:fermented_spider_eye",
    "minecraft:filled_map",
    "minecraft:fire_charge",
    "minecraft:firework_charge",
    "minecraft:fireworks",
    "minecraft:fish",
    "minecraft:fishing_rod",
    "minecraft:flint",
    "minecraft:flint_and_steel",
    "minecraft:flower_pot",
    "minecraft:furnace",
    "minecraft:furnace_minecart",
    "minecraft:ghast_tear",
    "minecraft:glass",
    "minecraft:glass_bottle",
    "minecraft:glass_pane",
    "minecraft:glowstone",
    "minecraft:glowstone_dust",
    "minecraft:gold_block",
    "minecraft:gold_ingot",
    "minecraft:gold_nugget",
    "minecraft:gold_ore",
    "minecraft:golden_apple",
    "minecraft:golden_axe",
    "minecraft:golden_boots",
    "minecraft:golden_carrot",
    "minecraft:golden_chestplate",
    "minecraft:golden_helmet",
    "minecraft:golden_hoe",
    "minecraft:golden_horse_armor",
    "minecraft:golden_leggings",
    "minecraft:golden_pickaxe",
    "minecraft:golden_rail",
    "minecraft:golden_shovel",
    "minecraft:golden_sword",
    "minecraft:grass",
    "minecraft:gravel",
    "minecraft:gunpowder",
    "minecraft:hardened_clay",
    "minecraft:hay_block",
    "minecraft:heavy_weighted_pressure_plate",
    "minecraft:hopper",
    "minecraft:hopper_minecart",
    "minecraft:ice",
    "minecraft:iron_axe",
    "minecraft:iron_bars",
    "minecraft:iron_block",
    "minecraft:iron_boots",
    "minecraft:iron_chestplate",
    "minecraft:iron_door",
    "minecraft:iron_helmet",
    "minecraft:iron_hoe",
    "minecraft:iron_horse_armor",
    "minecraft:iron_ingot",
    "minecraft:iron_leggings",
    "minecraft:iron_ore",
    "minecraft:iron_pickaxe",
    "minecraft:iron_shovel",
    "minecraft:iron_sword",
    "minecraft:iron_trapdoor",
    "minecraft:item_frame",
    "minecraft:jukebox",
    "minecraft:jungle_door",
    "minecraft:jungle_fence",
    "minecraft:jungle_fence_gate",
    "minecraft:jungle_stairs",
    "minecraft:ladder",
    "minecraft:lapis_block",
    "minecraft:lapis_ore",
    "minecraft:lava",
    "minecraft:lava_bucket",
    "minecraft:lead",
    "minecraft:leather",
    "minecraft:leather_boots",
    "minecraft:leather_chestplate",
    "minecraft:leather_helmet",
    "minecraft:leather_leggings",
    "minecraft:leaves",
    "minecraft:leaves2",
    "minecraft:lever",
    "minecraft:light_weighted_pressure_plate",
    "minecraft:lit_pumpkin",
    "minecraft:log",
    "minecraft:log2",
    "minecraft:magma_cream",
    "minecraft:map",
    "minecraft:melon",
    "minecraft:melon_block",
    "minecraft:melon_seeds",
    "minecraft:milk_bucket",
    "minecraft:minecart",
    "minecraft:mob_spawner",
    "minecraft:monster_egg",
    "minecraft:mossy_cobblestone",
    "minecraft:mushroom_stew",
    "minecraft:mutton",
    "minecraft:mycelium",
    "minecraft:name_tag",
    "minecraft:nether_brick",
    "minecraft:nether_brick_fence",
    "minecraft:nether_brick_stairs",
    "minecraft:nether_star",
    "minecraft:nether_wart",
    "minecraft:netherbrick",
    "minecraft:netherrack",
    "minecraft:noteblock",
    "minecraft:oak_stairs",
    "minecraft:obsidian",
    "minecraft:packed_ice",
    "minecraft:painting",
    "minecraft:paper",
    "minecraft:piston",
    "minecraft:planks",
    "minecraft:poisonous_potato",
    "minecraft:porkchop",
    "minecraft:potato",
    "minecraft:potion",
    "minecraft:prismarine",
    "minecraft:prismarine_crystals",
    "minecraft:prismarine_shard",
    "minecraft:pumpkin",
    "minecraft:pumpkin_pie",
    "minecraft:pumpkin_seeds",
    "minecraft:quartz",
    "minecraft:quartz_block",
    "minecraft:quartz_ore",
    "minecraft:quartz_stairs",
    "minecraft:rabbit",
    "minecraft:rabbit_foot",
    "minecraft:rabbit_hide",
    "minecraft:rabbit_stew",
    "minecraft:rail",
    "minecraft:record_11",
    "minecraft:record_13",
    "minecraft:record_blocks",
    "minecraft:record_cat",
    "minecraft:record_chirp",
    "minecraft:record_far",
    "minecraft:record_mall",
    "minecraft:record_mellohi",
    "minecraft:record_stal",
    "minecraft:record_strad",
    "minecraft:record_wait",
    "minecraft:record_ward",
    "minecraft:red_flower",
    "minecraft:red_mushroom",
    "minecraft:red_mushroom_block",
    "minecraft:red_sandstone",
    "minecraft:red_sandstone_stairs",
    "minecraft:redstone",
    "minecraft:redstone_block",
    "minecraft:redstone_lamp",
    "minecraft:redstone_ore",
    "minecraft:redstone_torch",
    "minecraft:reeds",
    "minecraft:repeater",
    "minecraft:rotten_flesh",
    "minecraft:saddle",
    "minecraft:sand",
    "minecraft:sandstone",
    "minecraft:sandstone_stairs",
    "minecraft:sapling",
    "minecraft:sea_lantern",
    "minecraft:shears",
    "minecraft:sign",
    "minecraft:skull",
    "minecraft:slime",
    "minecraft:slime_ball",
    "minecraft:snow",
    "minecraft:snow_layer",
    "minecraft:snowball",
    "minecraft:soul_sand",
    "minecraft:spawn_egg",
    "minecraft:speckled_melon",
    "minecraft:spider_eye",
    "minecraft:sponge",
    "minecraft:spruce_door",
    "minecraft:spruce_fence",
    "minecraft:spruce_fence_gate",
    "minecraft:spruce_stairs",
    "minecraft:stained_glass",
    "minecraft:stained_glass_pane",
    "minecraft:stained_hardened_clay",
    "minecraft:stick",
    "minecraft:sticky_piston",
    "minecraft:stone",
    "minecraft:stone_axe",
    "minecraft:stone_brick_stairs",
    "minecraft:stone_button",
    "minecraft:stone_hoe",
    "minecraft:stone_pickaxe",
    "minecraft:stone_pressure_plate",
    "minecraft:stone_shovel",
    "minecraft:stone_slab",
    "minecraft:stone_slab2",
    "minecraft:stone_stairs",
    "minecraft:stone_sword",
    "minecraft:stonebrick",
    "minecraft:string",
    "minecraft:sugar",
    "minecraft:tallgrass",
    "minecraft:tnt",
    "minecraft:tnt_minecart",
    "minecraft:torch",
    "minecraft:trapdoor",
    "minecraft:trapped_chest",
    "minecraft:tripwire_hook",
    "minecraft:vine",
    "minecraft:water",
    "minecraft:water_bucket",
    "minecraft:waterlily",
    "minecraft:web",
    "minecraft:wheat",
    "minecraft:wheat_seeds",
    "minecraft:wooden_axe",
    "minecraft:wooden_button",
    "minecraft:wooden_door",
    "minecraft:wooden_hoe",
    "minecraft:wooden_pickaxe",
    "minecraft:wooden_pressure_plate",
    "minecraft:wooden_shovel",
    "minecraft:wooden_slab",
    "minecraft:wooden_sword",
    "minecraft:wool",
    "minecraft:writable_book",
    "minecraft:written_book",
    "minecraft:yellow_flower",
]

type DisplayName = Literal[
    "Acacia Door",
    "Acacia Fence",
    "Acacia Fence Gate",
    "Acacia Leaves",
    "Acacia Log",
    "Acacia Planks",
    "Acacia Sapling",
    "Acacia Slab",
    "Acacia Stairs",
    "Activator Rails",
    "Air",
    "Allium",
    "Andesite",
    "Anvil",
    "Apple",
    "Armor Stand",
    "Arrow",
    "Azure Bluet",
    "Baked Potato",
    "Barrier",
    "Bat Spawn Egg",
    "Beacon",
    "Bedrock",
    "Birch Door",
    "Birch Fence",
    "Birch Fence Gate",
    "Birch Leaves",
    "Birch Log",
    "Birch Planks",
    "Birch Sapling",
    "Birch Slab",
    "Birch Stairs",
    "Black Banner",
    "Black Carpet",
    "Black Stained Glass",
    "Black Stained Glass Pane",
    "Black Terracotta",
    "Black Wool",
    "Blaze Powder",
    "Blaze Rod",
    "Blaze Spawn Egg",
    "Block of Diamond",
    "Block of Emerald",
    "Block of Gold",
    "Block of Iron",
    "Block of Melon",
    "Block of Nether Bricks",
    "Block of Quartz",
    "Block of Redstone",
    "Blue Banner",
    "Blue Carpet",
    "Blue Orchid",
    "Blue Stained Glass",
    "Blue Stained Glass Pane",
    "Blue Terracotta",
    "Blue Wool",
    "Bone",
    "Bone Meal",
    "Book",
    "Book and Quill",
    "Bookshelf",
    "Bottle o'Enchanting",
    "Bow",
    "Bowl",
    "Bread",
    "Brewing Stand",
    "Brick",
    "Brick Slab",
    "Brick Stairs",
    "Bricks",
    "Brown Banner",
    "Brown Carpet",
    "Brown Mushroom",
    "Brown Mushroom Block",
    "Brown Stained Glass",
    "Brown Stained Glass Pane",
    "Brown Terracotta",
    "Brown Wool",
    "Bucket",
    "Cactus",
    "Cake",
    "Carrot",
    "Carrot on a Stick",
    "Cauldron",
    "Cave Spider Spawn Egg",
    "Chain Boots",
    "Chain Chestplate",
    "Chain Helmet",
    "Chain Leggings",
    "Charcoal",
    "Chest",
    "Chicken Spawn Egg",
    "Chiseled Quartz Block",
    "Chiseled Red Sandstone",
    "Chiseled Sandstone",
    "Chiseled Stone Bricks",
    "Clay Ball",
    "Clay Block",
    "Clock",
    "Coal",
    "Coal Block",
    "Coal Ore",
    "Coarse Dirt",
    "Cobblestone",
    "Cobblestone Slab",
    "Cobblestone Stairs",
    "Cobblestone Wall",
    "Cobweb",
    "Cocoa Beans",
    "Command Block",
    "Compass",
    "Cooked Chicken",
    "Cooked Fish",
    "Cooked Mutton",
    "Cooked Porkchop",
    "Cooked Rabbit",
    "Cooked Salmon",
    "Cookie",
    "Cow Spawn Egg",
    "Cracked Stone Bricks",
    "Crafting Table",
    "Creeper Head",
    "Creeper Spawn Egg",
    "Cyan Banner",
    "Cyan Carpet",
    "Cyan Dye",
    "Cyan Stained Glass",
    "Cyan Stained Glass Pane",
    "Cyan Terracotta",
    "Cyan Wool",
    "Dandelion",
    "Dark Oak Door",
    "Dark Oak Fence",
    "Dark Oak Fence Gate",
    "Dark Oak Leaves",
    "Dark Oak Log",
    "Dark Oak Planks",
    "Dark Oak Sapling",
    "Dark Oak Slab",
    "Dark Oak Stairs",
    "Dark Prismarine",
    "Daylight Detector",
    "Dead Bush",
    "Detector Rails",
    "Diamond",
    "Diamond Axe",
    "Diamond Boots",
    "Diamond Chestplate",
    "Diamond Helmet",
    "Diamond Hoe",
    "Diamond Horse Armor",
    "Diamond Leggings",
    "Diamond Ore",
    "Diamond Pickaxe",
    "Diamond Shovel",
    "Diamond Sword",
    "Diorite",
    "Dirt",
    "Dispenser",
    "Dragon Egg",
    "Dropper",
    "Egg",
    "Emerald",
    "Emerald Ore",
    "Enchanted Book",
    "Enchanted Golden Apple",
    "Enchanting Table",
    "End Portal Frame",
    "End Stone",
    "Ender Chest",
    "Ender Pearl",
    "Enderman Spawn Egg",
    "Endermite Spawn Egg",
    "Eye of Ender",
    "Farmland",
    "Feather",
    "Fermented Spider Eye",
    "Fern",
    "Fire Charge",
    "Firework Rocket",
    "Firework Star",
    "Fishing Rod",
    "Flint",
    "Flint and Steel",
    "Flower Pot",
    "Furnace",
    "Ghast Spawn Egg",
    "Ghast Tear",
    "Glass",
    "Glass Bottle",
    "Glass Pane",
    "Glistering Melon Slice",
    "Glowstone",
    "Glowstone Dust",
    "Gold Horse Armor",
    "Gold Ingot",
    "Gold Nugget",
    "Gold Ore",
    "Golden Apple",
    "Golden Axe",
    "Golden Boots",
    "Golden Carrot",
    "Golden Chestplate",
    "Golden Helmet",
    "Golden Hoe",
    "Golden Leggings",
    "Golden Pickaxe",
    "Golden Shovel",
    "Golden Sword",
    "Granite",
    "Grass",
    "Grass Block",
    "Gravel",
    "Gray Banner",
    "Gray Carpet",
    "Gray Dye",
    "Gray Stained Glass",
    "Gray Stained Glass Pane",
    "Gray Terracotta",
    "Gray Wool",
    "Green Banner",
    "Green Carpet",
    "Green Dye",
    "Green Stained Glass",
    "Green Stained Glass Pane",
    "Green Terracotta",
    "Green Wool",
    "Guardian Spawn Egg",
    "Gunpowder",
    "Hay Bale",
    "Heavy Weighted Pressure Plate",
    "Hopper",
    "Horse Spawn Egg",
    "Ice",
    "Infested Chiseled Stone Bricks",
    "Infested Cobblestone",
    "Infested Cracked Stone Bricks",
    "Infested Mossy Stone Bricks",
    "Infested Stone",
    "Infested Stone Bricks",
    "Ink Sac",
    "Iron Axe",
    "Iron Bars",
    "Iron Boots",
    "Iron Chestplate",
    "Iron Door",
    "Iron Helmet",
    "Iron Hoe",
    "Iron Horse Armor",
    "Iron Ingot",
    "Iron Leggings",
    "Iron Ore",
    "Iron Pickaxe",
    "Iron Shovel",
    "Iron Sword",
    "Iron Trapdoor",
    "Item Frame",
    "Jack o'Lantern",
    "Jukebox",
    "Jungle Door",
    "Jungle Fence",
    "Jungle Fence Gate",
    "Jungle Leaves",
    "Jungle Log",
    "Jungle Planks",
    "Jungle Sapling",
    "Jungle Slab",
    "Jungle Stairs",
    "Ladder",
    "Lapis Lazuli",
    "Lapis Lazuli Block",
    "Lapis Lazuli Ore",
    "Large Fern",
    "Lava",
    "Lava Bucket",
    "Lead",
    "Leather",
    "Leather Boots",
    "Leather Cap",
    "Leather Pants",
    "Leather Tunic",
    "Lever",
    "Light Blue Banner",
    "Light Blue Carpet",
    "Light Blue Dye",
    "Light Blue Stained Glass",
    "Light Blue Stained Glass Pane",
    "Light Blue Terracotta",
    "Light Blue Wool",
    "Light Gray Banner",
    "Light Gray Carpet",
    "Light Gray Dye",
    "Light Gray Stained Glass",
    "Light Gray Stained Glass Pane",
    "Light Gray Terracotta",
    "Light Gray Wool",
    "Light Weighted Pressure Plate",
    "Lilac",
    "Lily Pad",
    "Lime Banner",
    "Lime Carpet",
    "Lime Dye",
    "Lime Stained Glass",
    "Lime Stained Glass Pane",
    "Lime Terracotta",
    "Lime Wool",
    "Magenta Banner",
    "Magenta Carpet",
    "Magenta Dye",
    "Magenta Stained Glass",
    "Magenta Stained Glass Pane",
    "Magenta Terracotta",
    "Magenta Wool",
    "Magma Cream",
    "Magma Cube Spawn Egg",
    "Map",
    "Map (Filled)",
    "Melon Seeds",
    "Melon Slice",
    "Milk Bucket",
    "Minecart",
    "Minecart with Chest",
    "Minecart with Command Block",
    "Minecart with Furnace",
    "Minecart with Hopper",
    "Minecart with TNT",
    "Monster Spawner",
    "Mooshroom Spawn Egg",
    "Mossy Cobblestone",
    "Mossy Cobblestone Wall",
    "Mossy Stone Bricks",
    "Mushroom Stew",
    "Music Disc (C418 - 11)",
    "Music Disc (C418 - 13)",
    "Music Disc (C418 - blocks)",
    "Music Disc (C418 - cat)",
    "Music Disc (C418 - chirp)",
    "Music Disc (C418 - far)",
    "Music Disc (C418 - mall)",
    "Music Disc (C418 - mellohi)",
    "Music Disc (C418 - stal)",
    "Music Disc (C418 - strad)",
    "Music Disc (C418 - wait)",
    "Music Disc (C418 - ward)",
    "Mycelium",
    "Name Tag",
    "Nether Brick",
    "Nether Brick Fence",
    "Nether Brick Slab",
    "Nether Brick Stairs",
    "Nether Quartz",
    "Nether Quartz Ore",
    "Nether Star",
    "Nether Wart",
    "Netherrack",
    "Note Block",
    "Oak Boat",
    "Oak Button",
    "Oak Door",
    "Oak Fence",
    "Oak Fence Gate",
    "Oak Leaves",
    "Oak Log",
    "Oak Planks",
    "Oak Pressure Plate",
    "Oak Sapling",
    "Oak Sign",
    "Oak Slab",
    "Oak Stairs",
    "Oak Trapdoor",
    "Obsidian",
    "Ocelot Spawn Egg",
    "Orange Banner",
    "Orange Carpet",
    "Orange Dye",
    "Orange Stained Glass",
    "Orange Stained Glass Pane",
    "Orange Terracotta",
    "Orange Tulip",
    "Orange Wool",
    "Oxeye Daisy",
    "Packed Ice",
    "Painting",
    "Paper",
    "Peony",
    "Pig Spawn Egg",
    "Pink Banner",
    "Pink Carpet",
    "Pink Dye",
    "Pink Stained Glass",
    "Pink Stained Glass Pane",
    "Pink Terracotta",
    "Pink Tulip",
    "Pink Wool",
    "Piston",
    "Player Head",
    "Podzol",
    "Poisonous Potato",
    "Polished Andesite",
    "Polished Diorite",
    "Polished Granite",
    "Poppy",
    "Potato",
    "Potion of Fire Resistance (3:00)",
    "Potion of Fire Resistance (8:00)",
    "Potion of Harming (Instant Damage II)",
    "Potion of Harming (Instant Damage)",
    "Potion of Healing (Instant Health II)",
    "Potion of Healing (Instant Health)",
    "Potion of Invisibility (3:00)",
    "Potion of Invisibility (8:00)",
    "Potion of Leaping (1:30 - Jump Boost II)",
    "Potion of Leaping (3:00 - Jump Boost)",
    "Potion of Leaping (8:00 - Jump Boost)",
    "Potion of Night Vision (3:00)",
    "Potion of Night Vision (8:00)",
    "Potion of Poison (0:21/0:22 - Poison II)",
    "Potion of Poison (0:45)",
    "Potion of Poison (1:30/2:00)",
    "Potion of Regeneration (0:22 - Regeneration II)",
    "Potion of Regeneration (0:45)",
    "Potion of Regeneration (1:30/2:00)",
    "Potion of Slowness (1:30)",
    "Potion of Slowness (4:00)",
    "Potion of Strength (1:30 - Strength II)",
    "Potion of Strength (3:00)",
    "Potion of Strength (8:00)",
    "Potion of Swiftness (1:30 - Speed II)",
    "Potion of Swiftness (3:00 - Speed)",
    "Potion of Swiftness (8:00 - Speed)",
    "Potion of Water Breathing (3:00)",
    "Potion of Water Breathing (8:00)",
    "Potion of Weakness (1:30)",
    "Potion of Weakness (4:00)",
    "Powered Rails",
    "Prismarine",
    "Prismarine Bricks",
    "Prismarine Crystals",
    "Prismarine Shard",
    "Pufferfish",
    "Pumpkin",
    "Pumpkin Pie",
    "Pumpkin Seeds",
    "Purple Banner",
    "Purple Carpet",
    "Purple Dye",
    "Purple Stained Glass",
    "Purple Stained Glass Pane",
    "Purple Terracotta",
    "Purple Wool",
    "Quartz Pillar",
    "Quartz Slab",
    "Quartz Stairs",
    "Rabbit Hide",
    "Rabbit Spawn Egg",
    "Rabbit Stew",
    "Rabbit's Foot",
    "Rails",
    "Raw Beef",
    "Raw Chicken",
    "Raw Fish",
    "Raw Mutton",
    "Raw Porkchop",
    "Raw Rabbit",
    "Raw Salmon",
    "Red Banner",
    "Red Bed",
    "Red Carpet",
    "Red Dye",
    "Red Mushroom",
    "Red Mushroom Block",
    "Red Sand",
    "Red Sandstone",
    "Red Sandstone Slab",
    "Red Sandstone Stairs",
    "Red Stained Glass",
    "Red Stained Glass Pane",
    "Red Terracotta",
    "Red Tulip",
    "Red Wool",
    "Redstone Comparator",
    "Redstone Dust",
    "Redstone Lamp",
    "Redstone Ore",
    "Redstone Repeater",
    "Redstone Torch",
    "Rose Bush",
    "Rotten Flesh",
    "Saddle",
    "Sand",
    "Sandstone",
    "Sandstone Slab",
    "Sandstone Stairs",
    "Sea Lantern",
    "Seeds",
    "Shears",
    "Sheep Spawn Egg",
    "Silverfish Spawn Egg",
    "Skeleton Skull",
    "Skeleton Spawn Egg",
    "Slightly Damaged Anvil",
    "Slime Block",
    "Slime Spawn Egg",
    "Slimeball",
    "Smooth Red Sandstone",
    "Smooth Sandstone",
    "Snow",
    "Snow Block",
    "Snowball",
    "Soul Sand",
    "Spider Eye",
    "Spider Spawn Egg",
    "Splash Potion of Fire Resistance (3:00/2:15)",
    "Splash Potion of Fire Resistance (8:00/6:00)",
    "Splash Potion of Harming (Instant Damage II)",
    "Splash Potion of Harming (Instant Damage)",
    "Splash Potion of Healing (Instant Health II)",
    "Splash Potion of Healing (Instant Health)",
    "Splash Potion of Invisibility (3:00/2:15)",
    "Splash Potion of Invisibility (8:00/6:00)",
    "Splash Potion of Leaping (1:30/1:07 - Jump Boost II)",
    "Splash Potion of Leaping (3:00/2:15 - Jump Boost)",
    "Splash Potion of Leaping (8:00/6:00 - Jump Boost)",
    "Splash Potion of Night Vision (3:00/2:15)",
    "Splash Potion of Night Vision (8:00/6:00)",
    "Splash Potion of Poison (0:21/0:16 - Poison II)",
    "Splash Potion of Poison (0:45/0:33)",
    "Splash Potion of Poison (1:30)",
    "Splash Potion of Regeneration (0:22/0:16 - Regeneration II)",
    "Splash Potion of Regeneration (0:45/0:33)",
    "Splash Potion of Regeneration (1:30)",
    "Splash Potion of Slowness (1:30/1:07)",
    "Splash Potion of Slowness (4:00/3:00)",
    "Splash Potion of Strength (1:30/1:07 - Strength II)",
    "Splash Potion of Strength (3:00/2:15)",
    "Splash Potion of Strength (8:00/6:00)",
    "Splash Potion of Swiftness (1:30/1:07 - Speed II)",
    "Splash Potion of Swiftness (3:00/2:15 - Speed)",
    "Splash Potion of Swiftness (8:00/6:00 - Speed)",
    "Splash Potion of Water Breathing (3:00/2:15)",
    "Splash Potion of Water Breathing (8:00/6:00)",
    "Splash Potion of Weakness (1:30/1:07)",
    "Splash Potion of Weakness (4:00/3:00)",
    "Sponge",
    "Spruce Door",
    "Spruce Fence",
    "Spruce Fence Gate",
    "Spruce Leaves",
    "Spruce Log",
    "Spruce Planks",
    "Spruce Sapling",
    "Spruce Slab",
    "Spruce Stairs",
    "Squid Spawn Egg",
    "Steak",
    "Stick",
    "Sticky Piston",
    "Stone",
    "Stone Axe",
    "Stone Brick Slab",
    "Stone Brick Stairs",
    "Stone Bricks",
    "Stone Button",
    "Stone Hoe",
    "Stone Pickaxe",
    "Stone Pressure Plate",
    "Stone Shovel",
    "Stone Slab",
    "Stone Sword",
    "String",
    "Sugar",
    "Sugar Canes",
    "Sunflower",
    "TNT",
    "Tall Grass",
    "Terracotta",
    "Torch",
    "Trapped Chest",
    "Tripwire Hook",
    "Tropical Fish (Clownfish)",
    "Very Damaged Anvil",
    "Villager Spawn Egg",
    "Vines",
    "Water",
    "Water Bottle",
    "Water Bucket",
    "Wet Sponge",
    "Wheat",
    "White Banner",
    "White Carpet",
    "White Stained Glass",
    "White Stained Glass Pane",
    "White Terracotta",
    "White Tulip",
    "White Wool",
    "Witch Spawn Egg",
    "Wither Skeleton Skull",
    "Wolf Spawn Egg",
    "Wooden Axe",
    "Wooden Hoe",
    "Wooden Pickaxe",
    "Wooden Shovel",
    "Wooden Sword",
    "Written Book",
    "Yellow Banner",
    "Yellow Carpet",
    "Yellow Dye",
    "Yellow Stained Glass",
    "Yellow Stained Glass Pane",
    "Yellow Terracotta",
    "Yellow Wool",
    "Zombie Head",
    "Zombie Spawn Egg",
    "Zombified Piglin Spawn Egg",
]

type ItemID = Literal[
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    35,
    37,
    38,
    39,
    40,
    41,
    42,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    52,
    53,
    54,
    56,
    57,
    58,
    60,
    61,
    65,
    66,
    67,
    69,
    70,
    72,
    73,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    84,
    85,
    86,
    87,
    88,
    89,
    91,
    95,
    96,
    97,
    98,
    99,
    100,
    101,
    102,
    103,
    106,
    107,
    108,
    109,
    110,
    111,
    112,
    113,
    114,
    116,
    120,
    121,
    122,
    123,
    126,
    128,
    129,
    130,
    131,
    133,
    134,
    135,
    136,
    137,
    138,
    139,
    143,
    145,
    146,
    147,
    148,
    151,
    152,
    153,
    154,
    155,
    156,
    157,
    158,
    159,
    160,
    161,
    162,
    163,
    164,
    165,
    166,
    167,
    168,
    169,
    170,
    171,
    172,
    173,
    174,
    175,
    179,
    180,
    182,
    183,
    184,
    185,
    186,
    187,
    188,
    189,
    190,
    191,
    192,
    256,
    257,
    258,
    259,
    260,
    261,
    262,
    263,
    264,
    265,
    266,
    267,
    268,
    269,
    270,
    271,
    272,
    273,
    274,
    275,
    276,
    277,
    278,
    279,
    280,
    281,
    282,
    283,
    284,
    285,
    286,
    287,
    288,
    289,
    290,
    291,
    292,
    293,
    294,
    295,
    296,
    297,
    298,
    299,
    300,
    301,
    302,
    303,
    304,
    305,
    306,
    307,
    308,
    309,
    310,
    311,
    312,
    313,
    314,
    315,
    316,
    317,
    318,
    319,
    320,
    321,
    322,
    323,
    324,
    325,
    326,
    327,
    328,
    329,
    330,
    331,
    332,
    333,
    334,
    335,
    336,
    337,
    338,
    339,
    340,
    341,
    342,
    343,
    344,
    345,
    346,
    347,
    348,
    349,
    350,
    351,
    352,
    353,
    354,
    355,
    356,
    357,
    358,
    359,
    360,
    361,
    362,
    363,
    364,
    365,
    366,
    367,
    368,
    369,
    370,
    371,
    372,
    373,
    374,
    375,
    376,
    377,
    378,
    379,
    380,
    381,
    382,
    383,
    384,
    385,
    386,
    387,
    388,
    389,
    390,
    391,
    392,
    393,
    394,
    395,
    396,
    397,
    398,
    399,
    400,
    401,
    402,
    403,
    404,
    405,
    406,
    407,
    408,
    409,
    410,
    411,
    412,
    413,
    414,
    415,
    416,
    417,
    418,
    419,
    420,
    421,
    422,
    423,
    424,
    425,
    427,
    428,
    429,
    430,
    431,
    2256,
    2257,
    2258,
    2259,
    2260,
    2261,
    2262,
    2263,
    2264,
    2265,
    2266,
    2267,
]
