// Auto-generated from petty/assets/_item_mapping.py
// (id, name, display_name, data)
pub static ITEMS: &[(u16, &str, &str, u16)] = &[
    (430, "minecraft:acacia_door", "Acacia Door", 0),
    (192, "minecraft:acacia_fence", "Acacia Fence", 0),
    (187, "minecraft:acacia_fence_gate", "Acacia Fence Gate", 0),
    (163, "minecraft:acacia_stairs", "Acacia Stairs", 0),
    (157, "minecraft:activator_rail", "Activator Rails", 0),
    (0, "minecraft:air", "Air", 0),
    (145, "minecraft:anvil", "Anvil", 0),
    (145, "minecraft:anvil", "Slightly Damaged Anvil", 1),
    (145, "minecraft:anvil", "Very Damaged Anvil", 2),
    (260, "minecraft:apple", "Apple", 0),
    (416, "minecraft:armor_stand", "Armor Stand", 0),
    (262, "minecraft:arrow", "Arrow", 0),
    (393, "minecraft:baked_potato", "Baked Potato", 0),
    (425, "minecraft:banner", "Black Banner", 0),
    (425, "minecraft:banner", "Red Banner", 1),
    (425, "minecraft:banner", "Green Banner", 2),
    (425, "minecraft:banner", "Brown Banner", 3),
    (425, "minecraft:banner", "Blue Banner", 4),
    (425, "minecraft:banner", "Purple Banner", 5),
    (425, "minecraft:banner", "Cyan Banner", 6),
    (425, "minecraft:banner", "Light Gray Banner", 7),
    (425, "minecraft:banner", "Gray Banner", 8),
    (425, "minecraft:banner", "Pink Banner", 9),
    (425, "minecraft:banner", "Lime Banner", 10),
    (425, "minecraft:banner", "Yellow Banner", 11),
    (425, "minecraft:banner", "Light Blue Banner", 12),
    (425, "minecraft:banner", "Magenta Banner", 13),
    (425, "minecraft:banner", "Orange Banner", 14),
    (425, "minecraft:banner", "White Banner", 15),
    (166, "minecraft:barrier", "Barrier", 0),
    (138, "minecraft:beacon", "Beacon", 0),
    (355, "minecraft:bed", "Red Bed", 0),
    (7, "minecraft:bedrock", "Bedrock", 0),
    (363, "minecraft:beef", "Raw Beef", 0),
    (428, "minecraft:birch_door", "Birch Door", 0),
    (189, "minecraft:birch_fence", "Birch Fence", 0),
    (184, "minecraft:birch_fence_gate", "Birch Fence Gate", 0),
    (135, "minecraft:birch_stairs", "Birch Stairs", 0),
    (377, "minecraft:blaze_powder", "Blaze Powder", 0),
    (369, "minecraft:blaze_rod", "Blaze Rod", 0),
    (333, "minecraft:boat", "Oak Boat", 0),
    (352, "minecraft:bone", "Bone", 0),
    (340, "minecraft:book", "Book", 0),
    (47, "minecraft:bookshelf", "Bookshelf", 0),
    (261, "minecraft:bow", "Bow", 0),
    (281, "minecraft:bowl", "Bowl", 0),
    (297, "minecraft:bread", "Bread", 0),
    (379, "minecraft:brewing_stand", "Brewing Stand", 0),
    (336, "minecraft:brick", "Brick", 0),
    (45, "minecraft:brick_block", "Bricks", 0),
    (108, "minecraft:brick_stairs", "Brick Stairs", 0),
    (39, "minecraft:brown_mushroom", "Brown Mushroom", 0),
    (
        99,
        "minecraft:brown_mushroom_block",
        "Brown Mushroom Block",
        0,
    ),
    (325, "minecraft:bucket", "Bucket", 0),
    (81, "minecraft:cactus", "Cactus", 0),
    (354, "minecraft:cake", "Cake", 0),
    (171, "minecraft:carpet", "White Carpet", 0),
    (171, "minecraft:carpet", "Orange Carpet", 1),
    (171, "minecraft:carpet", "Magenta Carpet", 2),
    (171, "minecraft:carpet", "Light Blue Carpet", 3),
    (171, "minecraft:carpet", "Yellow Carpet", 4),
    (171, "minecraft:carpet", "Lime Carpet", 5),
    (171, "minecraft:carpet", "Pink Carpet", 6),
    (171, "minecraft:carpet", "Gray Carpet", 7),
    (171, "minecraft:carpet", "Light Gray Carpet", 8),
    (171, "minecraft:carpet", "Cyan Carpet", 9),
    (171, "minecraft:carpet", "Purple Carpet", 10),
    (171, "minecraft:carpet", "Blue Carpet", 11),
    (171, "minecraft:carpet", "Brown Carpet", 12),
    (171, "minecraft:carpet", "Green Carpet", 13),
    (171, "minecraft:carpet", "Red Carpet", 14),
    (171, "minecraft:carpet", "Black Carpet", 15),
    (391, "minecraft:carrot", "Carrot", 0),
    (398, "minecraft:carrot_on_a_stick", "Carrot on a Stick", 0),
    (380, "minecraft:cauldron", "Cauldron", 0),
    (305, "minecraft:chainmail_boots", "Chain Boots", 0),
    (303, "minecraft:chainmail_chestplate", "Chain Chestplate", 0),
    (302, "minecraft:chainmail_helmet", "Chain Helmet", 0),
    (304, "minecraft:chainmail_leggings", "Chain Leggings", 0),
    (54, "minecraft:chest", "Chest", 0),
    (342, "minecraft:chest_minecart", "Minecart with Chest", 0),
    (365, "minecraft:chicken", "Raw Chicken", 0),
    (82, "minecraft:clay", "Clay Block", 0),
    (337, "minecraft:clay_ball", "Clay Ball", 0),
    (347, "minecraft:clock", "Clock", 0),
    (263, "minecraft:coal", "Coal", 0),
    (263, "minecraft:coal", "Charcoal", 1),
    (173, "minecraft:coal_block", "Coal Block", 0),
    (16, "minecraft:coal_ore", "Coal Ore", 0),
    (4, "minecraft:cobblestone", "Cobblestone", 0),
    (139, "minecraft:cobblestone_wall", "Cobblestone Wall", 0),
    (
        139,
        "minecraft:cobblestone_wall",
        "Mossy Cobblestone Wall",
        1,
    ),
    (137, "minecraft:command_block", "Command Block", 0),
    (
        422,
        "minecraft:command_block_minecart",
        "Minecart with Command Block",
        0,
    ),
    (404, "minecraft:comparator", "Redstone Comparator", 0),
    (345, "minecraft:compass", "Compass", 0),
    (364, "minecraft:cooked_beef", "Steak", 0),
    (366, "minecraft:cooked_chicken", "Cooked Chicken", 0),
    (350, "minecraft:cooked_fish", "Cooked Fish", 0),
    (350, "minecraft:cooked_fish", "Cooked Salmon", 1),
    (424, "minecraft:cooked_mutton", "Cooked Mutton", 0),
    (320, "minecraft:cooked_porkchop", "Cooked Porkchop", 0),
    (412, "minecraft:cooked_rabbit", "Cooked Rabbit", 0),
    (357, "minecraft:cookie", "Cookie", 0),
    (58, "minecraft:crafting_table", "Crafting Table", 0),
    (431, "minecraft:dark_oak_door", "Dark Oak Door", 0),
    (191, "minecraft:dark_oak_fence", "Dark Oak Fence", 0),
    (
        186,
        "minecraft:dark_oak_fence_gate",
        "Dark Oak Fence Gate",
        0,
    ),
    (164, "minecraft:dark_oak_stairs", "Dark Oak Stairs", 0),
    (151, "minecraft:daylight_detector", "Daylight Detector", 0),
    (32, "minecraft:deadbush", "Dead Bush", 0),
    (28, "minecraft:detector_rail", "Detector Rails", 0),
    (264, "minecraft:diamond", "Diamond", 0),
    (279, "minecraft:diamond_axe", "Diamond Axe", 0),
    (57, "minecraft:diamond_block", "Block of Diamond", 0),
    (313, "minecraft:diamond_boots", "Diamond Boots", 0),
    (311, "minecraft:diamond_chestplate", "Diamond Chestplate", 0),
    (310, "minecraft:diamond_helmet", "Diamond Helmet", 0),
    (293, "minecraft:diamond_hoe", "Diamond Hoe", 0),
    (
        419,
        "minecraft:diamond_horse_armor",
        "Diamond Horse Armor",
        0,
    ),
    (312, "minecraft:diamond_leggings", "Diamond Leggings", 0),
    (56, "minecraft:diamond_ore", "Diamond Ore", 0),
    (278, "minecraft:diamond_pickaxe", "Diamond Pickaxe", 0),
    (277, "minecraft:diamond_shovel", "Diamond Shovel", 0),
    (276, "minecraft:diamond_sword", "Diamond Sword", 0),
    (3, "minecraft:dirt", "Dirt", 0),
    (3, "minecraft:dirt", "Coarse Dirt", 1),
    (3, "minecraft:dirt", "Podzol", 2),
    (23, "minecraft:dispenser", "Dispenser", 0),
    (175, "minecraft:double_plant", "Sunflower", 0),
    (175, "minecraft:double_plant", "Lilac", 1),
    (175, "minecraft:double_plant", "Tall Grass", 2),
    (175, "minecraft:double_plant", "Large Fern", 3),
    (175, "minecraft:double_plant", "Rose Bush", 4),
    (175, "minecraft:double_plant", "Peony", 5),
    (122, "minecraft:dragon_egg", "Dragon Egg", 0),
    (158, "minecraft:dropper", "Dropper", 0),
    (351, "minecraft:dye", "Ink Sac", 0),
    (351, "minecraft:dye", "Red Dye", 1),
    (351, "minecraft:dye", "Green Dye", 2),
    (351, "minecraft:dye", "Cocoa Beans", 3),
    (351, "minecraft:dye", "Lapis Lazuli", 4),
    (351, "minecraft:dye", "Purple Dye", 5),
    (351, "minecraft:dye", "Cyan Dye", 6),
    (351, "minecraft:dye", "Light Gray Dye", 7),
    (351, "minecraft:dye", "Gray Dye", 8),
    (351, "minecraft:dye", "Pink Dye", 9),
    (351, "minecraft:dye", "Lime Dye", 10),
    (351, "minecraft:dye", "Yellow Dye", 11),
    (351, "minecraft:dye", "Light Blue Dye", 12),
    (351, "minecraft:dye", "Magenta Dye", 13),
    (351, "minecraft:dye", "Orange Dye", 14),
    (351, "minecraft:dye", "Bone Meal", 15),
    (344, "minecraft:egg", "Egg", 0),
    (388, "minecraft:emerald", "Emerald", 0),
    (133, "minecraft:emerald_block", "Block of Emerald", 0),
    (129, "minecraft:emerald_ore", "Emerald Ore", 0),
    (403, "minecraft:enchanted_book", "Enchanted Book", 0),
    (116, "minecraft:enchanting_table", "Enchanting Table", 0),
    (120, "minecraft:end_portal_frame", "End Portal Frame", 0),
    (121, "minecraft:end_stone", "End Stone", 0),
    (130, "minecraft:ender_chest", "Ender Chest", 0),
    (381, "minecraft:ender_eye", "Eye of Ender", 0),
    (368, "minecraft:ender_pearl", "Ender Pearl", 0),
    (384, "minecraft:experience_bottle", "Bottle o'Enchanting", 0),
    (60, "minecraft:farmland", "Farmland", 0),
    (288, "minecraft:feather", "Feather", 0),
    (85, "minecraft:fence", "Oak Fence", 0),
    (107, "minecraft:fence_gate", "Oak Fence Gate", 0),
    (
        376,
        "minecraft:fermented_spider_eye",
        "Fermented Spider Eye",
        0,
    ),
    (358, "minecraft:filled_map", "Map (Filled)", 0),
    (385, "minecraft:fire_charge", "Fire Charge", 0),
    (402, "minecraft:firework_charge", "Firework Star", 0),
    (401, "minecraft:fireworks", "Firework Rocket", 0),
    (349, "minecraft:fish", "Raw Fish", 0),
    (349, "minecraft:fish", "Raw Salmon", 1),
    (349, "minecraft:fish", "Tropical Fish (Clownfish)", 2),
    (349, "minecraft:fish", "Pufferfish", 3),
    (346, "minecraft:fishing_rod", "Fishing Rod", 0),
    (318, "minecraft:flint", "Flint", 0),
    (259, "minecraft:flint_and_steel", "Flint and Steel", 0),
    (390, "minecraft:flower_pot", "Flower Pot", 0),
    (61, "minecraft:furnace", "Furnace", 0),
    (
        343,
        "minecraft:furnace_minecart",
        "Minecart with Furnace",
        0,
    ),
    (370, "minecraft:ghast_tear", "Ghast Tear", 0),
    (20, "minecraft:glass", "Glass", 0),
    (374, "minecraft:glass_bottle", "Glass Bottle", 0),
    (102, "minecraft:glass_pane", "Glass Pane", 0),
    (89, "minecraft:glowstone", "Glowstone", 0),
    (348, "minecraft:glowstone_dust", "Glowstone Dust", 0),
    (41, "minecraft:gold_block", "Block of Gold", 0),
    (266, "minecraft:gold_ingot", "Gold Ingot", 0),
    (371, "minecraft:gold_nugget", "Gold Nugget", 0),
    (14, "minecraft:gold_ore", "Gold Ore", 0),
    (322, "minecraft:golden_apple", "Golden Apple", 0),
    (322, "minecraft:golden_apple", "Enchanted Golden Apple", 1),
    (286, "minecraft:golden_axe", "Golden Axe", 0),
    (317, "minecraft:golden_boots", "Golden Boots", 0),
    (396, "minecraft:golden_carrot", "Golden Carrot", 0),
    (315, "minecraft:golden_chestplate", "Golden Chestplate", 0),
    (314, "minecraft:golden_helmet", "Golden Helmet", 0),
    (294, "minecraft:golden_hoe", "Golden Hoe", 0),
    (418, "minecraft:golden_horse_armor", "Gold Horse Armor", 0),
    (316, "minecraft:golden_leggings", "Golden Leggings", 0),
    (285, "minecraft:golden_pickaxe", "Golden Pickaxe", 0),
    (27, "minecraft:golden_rail", "Powered Rails", 0),
    (284, "minecraft:golden_shovel", "Golden Shovel", 0),
    (283, "minecraft:golden_sword", "Golden Sword", 0),
    (2, "minecraft:grass", "Grass Block", 0),
    (13, "minecraft:gravel", "Gravel", 0),
    (289, "minecraft:gunpowder", "Gunpowder", 0),
    (172, "minecraft:hardened_clay", "Terracotta", 0),
    (170, "minecraft:hay_block", "Hay Bale", 0),
    (
        148,
        "minecraft:heavy_weighted_pressure_plate",
        "Heavy Weighted Pressure Plate",
        0,
    ),
    (154, "minecraft:hopper", "Hopper", 0),
    (408, "minecraft:hopper_minecart", "Minecart with Hopper", 0),
    (79, "minecraft:ice", "Ice", 0),
    (258, "minecraft:iron_axe", "Iron Axe", 0),
    (101, "minecraft:iron_bars", "Iron Bars", 0),
    (42, "minecraft:iron_block", "Block of Iron", 0),
    (309, "minecraft:iron_boots", "Iron Boots", 0),
    (307, "minecraft:iron_chestplate", "Iron Chestplate", 0),
    (330, "minecraft:iron_door", "Iron Door", 0),
    (306, "minecraft:iron_helmet", "Iron Helmet", 0),
    (292, "minecraft:iron_hoe", "Iron Hoe", 0),
    (417, "minecraft:iron_horse_armor", "Iron Horse Armor", 0),
    (265, "minecraft:iron_ingot", "Iron Ingot", 0),
    (308, "minecraft:iron_leggings", "Iron Leggings", 0),
    (15, "minecraft:iron_ore", "Iron Ore", 0),
    (257, "minecraft:iron_pickaxe", "Iron Pickaxe", 0),
    (256, "minecraft:iron_shovel", "Iron Shovel", 0),
    (267, "minecraft:iron_sword", "Iron Sword", 0),
    (167, "minecraft:iron_trapdoor", "Iron Trapdoor", 0),
    (389, "minecraft:item_frame", "Item Frame", 0),
    (84, "minecraft:jukebox", "Jukebox", 0),
    (429, "minecraft:jungle_door", "Jungle Door", 0),
    (190, "minecraft:jungle_fence", "Jungle Fence", 0),
    (185, "minecraft:jungle_fence_gate", "Jungle Fence Gate", 0),
    (136, "minecraft:jungle_stairs", "Jungle Stairs", 0),
    (65, "minecraft:ladder", "Ladder", 0),
    (22, "minecraft:lapis_block", "Lapis Lazuli Block", 0),
    (21, "minecraft:lapis_ore", "Lapis Lazuli Ore", 0),
    (0, "minecraft:lava", "Lava", 0),
    (327, "minecraft:lava_bucket", "Lava Bucket", 0),
    (420, "minecraft:lead", "Lead", 0),
    (334, "minecraft:leather", "Leather", 0),
    (301, "minecraft:leather_boots", "Leather Boots", 0),
    (299, "minecraft:leather_chestplate", "Leather Tunic", 0),
    (298, "minecraft:leather_helmet", "Leather Cap", 0),
    (300, "minecraft:leather_leggings", "Leather Pants", 0),
    (18, "minecraft:leaves", "Oak Leaves", 0),
    (18, "minecraft:leaves", "Spruce Leaves", 1),
    (18, "minecraft:leaves", "Birch Leaves", 2),
    (18, "minecraft:leaves", "Jungle Leaves", 3),
    (161, "minecraft:leaves2", "Acacia Leaves", 0),
    (161, "minecraft:leaves2", "Dark Oak Leaves", 1),
    (69, "minecraft:lever", "Lever", 0),
    (
        147,
        "minecraft:light_weighted_pressure_plate",
        "Light Weighted Pressure Plate",
        0,
    ),
    (91, "minecraft:lit_pumpkin", "Jack o'Lantern", 0),
    (17, "minecraft:log", "Oak Log", 0),
    (17, "minecraft:log", "Spruce Log", 1),
    (17, "minecraft:log", "Birch Log", 2),
    (17, "minecraft:log", "Jungle Log", 3),
    (162, "minecraft:log2", "Acacia Log", 0),
    (162, "minecraft:log2", "Dark Oak Log", 1),
    (378, "minecraft:magma_cream", "Magma Cream", 0),
    (395, "minecraft:map", "Map", 0),
    (360, "minecraft:melon", "Melon Slice", 0),
    (103, "minecraft:melon_block", "Block of Melon", 0),
    (362, "minecraft:melon_seeds", "Melon Seeds", 0),
    (335, "minecraft:milk_bucket", "Milk Bucket", 0),
    (328, "minecraft:minecart", "Minecart", 0),
    (52, "minecraft:mob_spawner", "Monster Spawner", 0),
    (97, "minecraft:monster_egg", "Infested Stone", 0),
    (97, "minecraft:monster_egg", "Infested Cobblestone", 1),
    (97, "minecraft:monster_egg", "Infested Stone Bricks", 2),
    (
        97,
        "minecraft:monster_egg",
        "Infested Mossy Stone Bricks",
        3,
    ),
    (
        97,
        "minecraft:monster_egg",
        "Infested Cracked Stone Bricks",
        4,
    ),
    (
        97,
        "minecraft:monster_egg",
        "Infested Chiseled Stone Bricks",
        5,
    ),
    (48, "minecraft:mossy_cobblestone", "Mossy Cobblestone", 0),
    (282, "minecraft:mushroom_stew", "Mushroom Stew", 0),
    (423, "minecraft:mutton", "Raw Mutton", 0),
    (110, "minecraft:mycelium", "Mycelium", 0),
    (421, "minecraft:name_tag", "Name Tag", 0),
    (112, "minecraft:nether_brick", "Block of Nether Bricks", 0),
    (113, "minecraft:nether_brick_fence", "Nether Brick Fence", 0),
    (
        114,
        "minecraft:nether_brick_stairs",
        "Nether Brick Stairs",
        0,
    ),
    (399, "minecraft:nether_star", "Nether Star", 0),
    (372, "minecraft:nether_wart", "Nether Wart", 0),
    (405, "minecraft:netherbrick", "Nether Brick", 0),
    (87, "minecraft:netherrack", "Netherrack", 0),
    (25, "minecraft:noteblock", "Note Block", 0),
    (53, "minecraft:oak_stairs", "Oak Stairs", 0),
    (49, "minecraft:obsidian", "Obsidian", 0),
    (174, "minecraft:packed_ice", "Packed Ice", 0),
    (321, "minecraft:painting", "Painting", 0),
    (339, "minecraft:paper", "Paper", 0),
    (33, "minecraft:piston", "Piston", 0),
    (5, "minecraft:planks", "Oak Planks", 0),
    (5, "minecraft:planks", "Spruce Planks", 1),
    (5, "minecraft:planks", "Birch Planks", 2),
    (5, "minecraft:planks", "Jungle Planks", 3),
    (5, "minecraft:planks", "Acacia Planks", 4),
    (5, "minecraft:planks", "Dark Oak Planks", 5),
    (394, "minecraft:poisonous_potato", "Poisonous Potato", 0),
    (319, "minecraft:porkchop", "Raw Porkchop", 0),
    (392, "minecraft:potato", "Potato", 0),
    (373, "minecraft:potion", "Water Bottle", 0),
    (
        373,
        "minecraft:potion",
        "Potion of Regeneration (0:45)",
        8193,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Swiftness (3:00 - Speed)",
        8194,
    ),
    (373, "minecraft:potion", "Potion of Poison (0:45)", 8196),
    (373, "minecraft:potion", "Potion of Strength (3:00)", 8201),
    (
        373,
        "minecraft:potion",
        "Potion of Leaping (3:00 - Jump Boost)",
        8203,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Regeneration (0:22 - Regeneration II)",
        8225,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Swiftness (1:30 - Speed II)",
        8226,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Fire Resistance (3:00)",
        8227,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Poison (0:21/0:22 - Poison II)",
        8228,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Healing (Instant Health II)",
        8229,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Night Vision (3:00)",
        8230,
    ),
    (373, "minecraft:potion", "Potion of Weakness (1:30)", 8232),
    (
        373,
        "minecraft:potion",
        "Potion of Strength (1:30 - Strength II)",
        8233,
    ),
    (373, "minecraft:potion", "Potion of Slowness (1:30)", 8234),
    (
        373,
        "minecraft:potion",
        "Potion of Leaping (1:30 - Jump Boost II)",
        8235,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Harming (Instant Damage II)",
        8236,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Water Breathing (3:00)",
        8237,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Invisibility (3:00)",
        8238,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Regeneration (1:30/2:00)",
        8257,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Swiftness (8:00 - Speed)",
        8258,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Fire Resistance (8:00)",
        8259,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Poison (1:30/2:00)",
        8260,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Healing (Instant Health)",
        8261,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Night Vision (8:00)",
        8262,
    ),
    (373, "minecraft:potion", "Potion of Weakness (4:00)", 8264),
    (373, "minecraft:potion", "Potion of Strength (8:00)", 8265),
    (373, "minecraft:potion", "Potion of Slowness (4:00)", 8266),
    (
        373,
        "minecraft:potion",
        "Potion of Leaping (8:00 - Jump Boost)",
        8267,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Harming (Instant Damage)",
        8268,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Water Breathing (8:00)",
        8269,
    ),
    (
        373,
        "minecraft:potion",
        "Potion of Invisibility (8:00)",
        8270,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Regeneration (0:45/0:33)",
        16385,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Swiftness (3:00/2:15 - Speed)",
        16386,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Poison (0:45/0:33)",
        16388,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Strength (3:00/2:15)",
        16393,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Leaping (3:00/2:15 - Jump Boost)",
        16395,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Regeneration (0:22/0:16 - Regeneration II)",
        16417,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Swiftness (1:30/1:07 - Speed II)",
        16418,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Fire Resistance (3:00/2:15)",
        16419,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Poison (0:21/0:16 - Poison II)",
        16420,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Healing (Instant Health II)",
        16421,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Night Vision (3:00/2:15)",
        16422,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Weakness (1:30/1:07)",
        16424,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Strength (1:30/1:07 - Strength II)",
        16425,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Slowness (1:30/1:07)",
        16426,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Leaping (1:30/1:07 - Jump Boost II)",
        16427,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Harming (Instant Damage II)",
        16428,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Water Breathing (3:00/2:15)",
        16429,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Invisibility (3:00/2:15)",
        16430,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Regeneration (1:30)",
        16449,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Swiftness (8:00/6:00 - Speed)",
        16450,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Fire Resistance (8:00/6:00)",
        16451,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Poison (1:30)",
        16452,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Healing (Instant Health)",
        16453,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Night Vision (8:00/6:00)",
        16454,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Weakness (4:00/3:00)",
        16456,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Strength (8:00/6:00)",
        16457,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Slowness (4:00/3:00)",
        16458,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Leaping (8:00/6:00 - Jump Boost)",
        16459,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Harming (Instant Damage)",
        16460,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Water Breathing (8:00/6:00)",
        16461,
    ),
    (
        373,
        "minecraft:potion",
        "Splash Potion of Invisibility (8:00/6:00)",
        16462,
    ),
    (168, "minecraft:prismarine", "Prismarine", 0),
    (168, "minecraft:prismarine", "Prismarine Bricks", 1),
    (168, "minecraft:prismarine", "Dark Prismarine", 2),
    (
        410,
        "minecraft:prismarine_crystals",
        "Prismarine Crystals",
        0,
    ),
    (409, "minecraft:prismarine_shard", "Prismarine Shard", 0),
    (86, "minecraft:pumpkin", "Pumpkin", 0),
    (400, "minecraft:pumpkin_pie", "Pumpkin Pie", 0),
    (361, "minecraft:pumpkin_seeds", "Pumpkin Seeds", 0),
    (406, "minecraft:quartz", "Nether Quartz", 0),
    (155, "minecraft:quartz_block", "Block of Quartz", 0),
    (155, "minecraft:quartz_block", "Chiseled Quartz Block", 1),
    (155, "minecraft:quartz_block", "Quartz Pillar", 2),
    (153, "minecraft:quartz_ore", "Nether Quartz Ore", 0),
    (156, "minecraft:quartz_stairs", "Quartz Stairs", 0),
    (411, "minecraft:rabbit", "Raw Rabbit", 0),
    (414, "minecraft:rabbit_foot", "Rabbit's Foot", 0),
    (415, "minecraft:rabbit_hide", "Rabbit Hide", 0),
    (413, "minecraft:rabbit_stew", "Rabbit Stew", 0),
    (66, "minecraft:rail", "Rails", 0),
    (2266, "minecraft:record_11", "Music Disc (C418 - 11)", 0),
    (2256, "minecraft:record_13", "Music Disc (C418 - 13)", 0),
    (
        2258,
        "minecraft:record_blocks",
        "Music Disc (C418 - blocks)",
        0,
    ),
    (2257, "minecraft:record_cat", "Music Disc (C418 - cat)", 0),
    (
        2259,
        "minecraft:record_chirp",
        "Music Disc (C418 - chirp)",
        0,
    ),
    (2260, "minecraft:record_far", "Music Disc (C418 - far)", 0),
    (2261, "minecraft:record_mall", "Music Disc (C418 - mall)", 0),
    (
        2262,
        "minecraft:record_mellohi",
        "Music Disc (C418 - mellohi)",
        0,
    ),
    (2263, "minecraft:record_stal", "Music Disc (C418 - stal)", 0),
    (
        2264,
        "minecraft:record_strad",
        "Music Disc (C418 - strad)",
        0,
    ),
    (2267, "minecraft:record_wait", "Music Disc (C418 - wait)", 0),
    (2265, "minecraft:record_ward", "Music Disc (C418 - ward)", 0),
    (38, "minecraft:red_flower", "Poppy", 0),
    (38, "minecraft:red_flower", "Blue Orchid", 1),
    (38, "minecraft:red_flower", "Allium", 2),
    (38, "minecraft:red_flower", "Azure Bluet", 3),
    (38, "minecraft:red_flower", "Red Tulip", 4),
    (38, "minecraft:red_flower", "Orange Tulip", 5),
    (38, "minecraft:red_flower", "White Tulip", 6),
    (38, "minecraft:red_flower", "Pink Tulip", 7),
    (38, "minecraft:red_flower", "Oxeye Daisy", 8),
    (40, "minecraft:red_mushroom", "Red Mushroom", 0),
    (100, "minecraft:red_mushroom_block", "Red Mushroom Block", 0),
    (179, "minecraft:red_sandstone", "Red Sandstone", 0),
    (179, "minecraft:red_sandstone", "Chiseled Red Sandstone", 1),
    (179, "minecraft:red_sandstone", "Smooth Red Sandstone", 2),
    (
        180,
        "minecraft:red_sandstone_stairs",
        "Red Sandstone Stairs",
        0,
    ),
    (331, "minecraft:redstone", "Redstone Dust", 0),
    (152, "minecraft:redstone_block", "Block of Redstone", 0),
    (123, "minecraft:redstone_lamp", "Redstone Lamp", 0),
    (73, "minecraft:redstone_ore", "Redstone Ore", 0),
    (76, "minecraft:redstone_torch", "Redstone Torch", 0),
    (338, "minecraft:reeds", "Sugar Canes", 0),
    (356, "minecraft:repeater", "Redstone Repeater", 0),
    (367, "minecraft:rotten_flesh", "Rotten Flesh", 0),
    (329, "minecraft:saddle", "Saddle", 0),
    (12, "minecraft:sand", "Sand", 0),
    (12, "minecraft:sand", "Red Sand", 1),
    (24, "minecraft:sandstone", "Sandstone", 0),
    (24, "minecraft:sandstone", "Chiseled Sandstone", 1),
    (24, "minecraft:sandstone", "Smooth Sandstone", 2),
    (128, "minecraft:sandstone_stairs", "Sandstone Stairs", 0),
    (6, "minecraft:sapling", "Oak Sapling", 0),
    (6, "minecraft:sapling", "Spruce Sapling", 1),
    (6, "minecraft:sapling", "Birch Sapling", 2),
    (6, "minecraft:sapling", "Jungle Sapling", 3),
    (6, "minecraft:sapling", "Acacia Sapling", 4),
    (6, "minecraft:sapling", "Dark Oak Sapling", 5),
    (169, "minecraft:sea_lantern", "Sea Lantern", 0),
    (359, "minecraft:shears", "Shears", 0),
    (323, "minecraft:sign", "Oak Sign", 0),
    (397, "minecraft:skull", "Skeleton Skull", 0),
    (397, "minecraft:skull", "Wither Skeleton Skull", 1),
    (397, "minecraft:skull", "Zombie Head", 2),
    (397, "minecraft:skull", "Player Head", 3),
    (397, "minecraft:skull", "Creeper Head", 4),
    (165, "minecraft:slime", "Slime Block", 0),
    (341, "minecraft:slime_ball", "Slimeball", 0),
    (80, "minecraft:snow", "Snow Block", 0),
    (78, "minecraft:snow_layer", "Snow", 0),
    (332, "minecraft:snowball", "Snowball", 0),
    (88, "minecraft:soul_sand", "Soul Sand", 0),
    (383, "minecraft:spawn_egg", "Creeper Spawn Egg", 50),
    (383, "minecraft:spawn_egg", "Skeleton Spawn Egg", 51),
    (383, "minecraft:spawn_egg", "Spider Spawn Egg", 52),
    (383, "minecraft:spawn_egg", "Zombie Spawn Egg", 54),
    (383, "minecraft:spawn_egg", "Slime Spawn Egg", 55),
    (383, "minecraft:spawn_egg", "Ghast Spawn Egg", 56),
    (383, "minecraft:spawn_egg", "Zombified Piglin Spawn Egg", 57),
    (383, "minecraft:spawn_egg", "Enderman Spawn Egg", 58),
    (383, "minecraft:spawn_egg", "Cave Spider Spawn Egg", 59),
    (383, "minecraft:spawn_egg", "Silverfish Spawn Egg", 60),
    (383, "minecraft:spawn_egg", "Blaze Spawn Egg", 61),
    (383, "minecraft:spawn_egg", "Magma Cube Spawn Egg", 62),
    (383, "minecraft:spawn_egg", "Bat Spawn Egg", 65),
    (383, "minecraft:spawn_egg", "Witch Spawn Egg", 66),
    (383, "minecraft:spawn_egg", "Endermite Spawn Egg", 67),
    (383, "minecraft:spawn_egg", "Guardian Spawn Egg", 68),
    (383, "minecraft:spawn_egg", "Pig Spawn Egg", 90),
    (383, "minecraft:spawn_egg", "Sheep Spawn Egg", 91),
    (383, "minecraft:spawn_egg", "Cow Spawn Egg", 92),
    (383, "minecraft:spawn_egg", "Chicken Spawn Egg", 93),
    (383, "minecraft:spawn_egg", "Squid Spawn Egg", 94),
    (383, "minecraft:spawn_egg", "Wolf Spawn Egg", 95),
    (383, "minecraft:spawn_egg", "Mooshroom Spawn Egg", 96),
    (383, "minecraft:spawn_egg", "Ocelot Spawn Egg", 98),
    (383, "minecraft:spawn_egg", "Horse Spawn Egg", 100),
    (383, "minecraft:spawn_egg", "Rabbit Spawn Egg", 101),
    (383, "minecraft:spawn_egg", "Villager Spawn Egg", 120),
    (382, "minecraft:speckled_melon", "Glistering Melon Slice", 0),
    (375, "minecraft:spider_eye", "Spider Eye", 0),
    (19, "minecraft:sponge", "Sponge", 0),
    (19, "minecraft:sponge", "Wet Sponge", 1),
    (427, "minecraft:spruce_door", "Spruce Door", 0),
    (188, "minecraft:spruce_fence", "Spruce Fence", 0),
    (183, "minecraft:spruce_fence_gate", "Spruce Fence Gate", 0),
    (134, "minecraft:spruce_stairs", "Spruce Stairs", 0),
    (95, "minecraft:stained_glass", "White Stained Glass", 0),
    (95, "minecraft:stained_glass", "Orange Stained Glass", 1),
    (95, "minecraft:stained_glass", "Magenta Stained Glass", 2),
    (95, "minecraft:stained_glass", "Light Blue Stained Glass", 3),
    (95, "minecraft:stained_glass", "Yellow Stained Glass", 4),
    (95, "minecraft:stained_glass", "Lime Stained Glass", 5),
    (95, "minecraft:stained_glass", "Pink Stained Glass", 6),
    (95, "minecraft:stained_glass", "Gray Stained Glass", 7),
    (95, "minecraft:stained_glass", "Light Gray Stained Glass", 8),
    (95, "minecraft:stained_glass", "Cyan Stained Glass", 9),
    (95, "minecraft:stained_glass", "Purple Stained Glass", 10),
    (95, "minecraft:stained_glass", "Blue Stained Glass", 11),
    (95, "minecraft:stained_glass", "Brown Stained Glass", 12),
    (95, "minecraft:stained_glass", "Green Stained Glass", 13),
    (95, "minecraft:stained_glass", "Red Stained Glass", 14),
    (95, "minecraft:stained_glass", "Black Stained Glass", 15),
    (
        160,
        "minecraft:stained_glass_pane",
        "White Stained Glass Pane",
        0,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Orange Stained Glass Pane",
        1,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Magenta Stained Glass Pane",
        2,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Light Blue Stained Glass Pane",
        3,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Yellow Stained Glass Pane",
        4,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Lime Stained Glass Pane",
        5,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Pink Stained Glass Pane",
        6,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Gray Stained Glass Pane",
        7,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Light Gray Stained Glass Pane",
        8,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Cyan Stained Glass Pane",
        9,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Purple Stained Glass Pane",
        10,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Blue Stained Glass Pane",
        11,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Brown Stained Glass Pane",
        12,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Green Stained Glass Pane",
        13,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Red Stained Glass Pane",
        14,
    ),
    (
        160,
        "minecraft:stained_glass_pane",
        "Black Stained Glass Pane",
        15,
    ),
    (
        159,
        "minecraft:stained_hardened_clay",
        "White Terracotta",
        0,
    ),
    (
        159,
        "minecraft:stained_hardened_clay",
        "Orange Terracotta",
        1,
    ),
    (
        159,
        "minecraft:stained_hardened_clay",
        "Magenta Terracotta",
        2,
    ),
    (
        159,
        "minecraft:stained_hardened_clay",
        "Light Blue Terracotta",
        3,
    ),
    (
        159,
        "minecraft:stained_hardened_clay",
        "Yellow Terracotta",
        4,
    ),
    (159, "minecraft:stained_hardened_clay", "Lime Terracotta", 5),
    (159, "minecraft:stained_hardened_clay", "Pink Terracotta", 6),
    (159, "minecraft:stained_hardened_clay", "Gray Terracotta", 7),
    (
        159,
        "minecraft:stained_hardened_clay",
        "Light Gray Terracotta",
        8,
    ),
    (159, "minecraft:stained_hardened_clay", "Cyan Terracotta", 9),
    (
        159,
        "minecraft:stained_hardened_clay",
        "Purple Terracotta",
        10,
    ),
    (
        159,
        "minecraft:stained_hardened_clay",
        "Blue Terracotta",
        11,
    ),
    (
        159,
        "minecraft:stained_hardened_clay",
        "Brown Terracotta",
        12,
    ),
    (
        159,
        "minecraft:stained_hardened_clay",
        "Green Terracotta",
        13,
    ),
    (159, "minecraft:stained_hardened_clay", "Red Terracotta", 14),
    (
        159,
        "minecraft:stained_hardened_clay",
        "Black Terracotta",
        15,
    ),
    (280, "minecraft:stick", "Stick", 0),
    (29, "minecraft:sticky_piston", "Sticky Piston", 0),
    (1, "minecraft:stone", "Stone", 0),
    (1, "minecraft:stone", "Granite", 1),
    (1, "minecraft:stone", "Polished Granite", 2),
    (1, "minecraft:stone", "Diorite", 3),
    (1, "minecraft:stone", "Polished Diorite", 4),
    (1, "minecraft:stone", "Andesite", 5),
    (1, "minecraft:stone", "Polished Andesite", 6),
    (275, "minecraft:stone_axe", "Stone Axe", 0),
    (109, "minecraft:stone_brick_stairs", "Stone Brick Stairs", 0),
    (77, "minecraft:stone_button", "Stone Button", 0),
    (291, "minecraft:stone_hoe", "Stone Hoe", 0),
    (274, "minecraft:stone_pickaxe", "Stone Pickaxe", 0),
    (
        70,
        "minecraft:stone_pressure_plate",
        "Stone Pressure Plate",
        0,
    ),
    (273, "minecraft:stone_shovel", "Stone Shovel", 0),
    (44, "minecraft:stone_slab", "Stone Slab", 0),
    (44, "minecraft:stone_slab", "Sandstone Slab", 1),
    (44, "minecraft:stone_slab", "Cobblestone Slab", 3),
    (44, "minecraft:stone_slab", "Brick Slab", 4),
    (44, "minecraft:stone_slab", "Stone Brick Slab", 5),
    (44, "minecraft:stone_slab", "Nether Brick Slab", 6),
    (44, "minecraft:stone_slab", "Quartz Slab", 7),
    (182, "minecraft:stone_slab2", "Red Sandstone Slab", 0),
    (67, "minecraft:stone_stairs", "Cobblestone Stairs", 0),
    (272, "minecraft:stone_sword", "Stone Sword", 0),
    (98, "minecraft:stonebrick", "Stone Bricks", 0),
    (98, "minecraft:stonebrick", "Mossy Stone Bricks", 1),
    (98, "minecraft:stonebrick", "Cracked Stone Bricks", 2),
    (98, "minecraft:stonebrick", "Chiseled Stone Bricks", 3),
    (287, "minecraft:string", "String", 0),
    (353, "minecraft:sugar", "Sugar", 0),
    (31, "minecraft:tallgrass", "Grass", 1),
    (31, "minecraft:tallgrass", "Fern", 2),
    (46, "minecraft:tnt", "TNT", 0),
    (407, "minecraft:tnt_minecart", "Minecart with TNT", 0),
    (50, "minecraft:torch", "Torch", 0),
    (96, "minecraft:trapdoor", "Oak Trapdoor", 0),
    (146, "minecraft:trapped_chest", "Trapped Chest", 0),
    (131, "minecraft:tripwire_hook", "Tripwire Hook", 0),
    (106, "minecraft:vine", "Vines", 0),
    (0, "minecraft:water", "Water", 0),
    (326, "minecraft:water_bucket", "Water Bucket", 0),
    (111, "minecraft:waterlily", "Lily Pad", 0),
    (30, "minecraft:web", "Cobweb", 0),
    (296, "minecraft:wheat", "Wheat", 0),
    (295, "minecraft:wheat_seeds", "Seeds", 0),
    (271, "minecraft:wooden_axe", "Wooden Axe", 0),
    (143, "minecraft:wooden_button", "Oak Button", 0),
    (324, "minecraft:wooden_door", "Oak Door", 0),
    (290, "minecraft:wooden_hoe", "Wooden Hoe", 0),
    (270, "minecraft:wooden_pickaxe", "Wooden Pickaxe", 0),
    (
        72,
        "minecraft:wooden_pressure_plate",
        "Oak Pressure Plate",
        0,
    ),
    (269, "minecraft:wooden_shovel", "Wooden Shovel", 0),
    (126, "minecraft:wooden_slab", "Oak Slab", 0),
    (126, "minecraft:wooden_slab", "Spruce Slab", 1),
    (126, "minecraft:wooden_slab", "Birch Slab", 2),
    (126, "minecraft:wooden_slab", "Jungle Slab", 3),
    (126, "minecraft:wooden_slab", "Acacia Slab", 4),
    (126, "minecraft:wooden_slab", "Dark Oak Slab", 5),
    (268, "minecraft:wooden_sword", "Wooden Sword", 0),
    (35, "minecraft:wool", "White Wool", 0),
    (35, "minecraft:wool", "Orange Wool", 1),
    (35, "minecraft:wool", "Magenta Wool", 2),
    (35, "minecraft:wool", "Light Blue Wool", 3),
    (35, "minecraft:wool", "Yellow Wool", 4),
    (35, "minecraft:wool", "Lime Wool", 5),
    (35, "minecraft:wool", "Pink Wool", 6),
    (35, "minecraft:wool", "Gray Wool", 7),
    (35, "minecraft:wool", "Light Gray Wool", 8),
    (35, "minecraft:wool", "Cyan Wool", 9),
    (35, "minecraft:wool", "Purple Wool", 10),
    (35, "minecraft:wool", "Blue Wool", 11),
    (35, "minecraft:wool", "Brown Wool", 12),
    (35, "minecraft:wool", "Green Wool", 13),
    (35, "minecraft:wool", "Red Wool", 14),
    (35, "minecraft:wool", "Black Wool", 15),
    (386, "minecraft:writable_book", "Book and Quill", 0),
    (387, "minecraft:written_book", "Written Book", 0),
    (37, "minecraft:yellow_flower", "Dandelion", 0),
];
