name: Lint

on:
  pull_request:
    paths:
      - "**/*.py"
      - "**/*.rs"
      - "pyproject.toml"
      - "Cargo.toml"
      - ".pre-commit-config.yaml"
      - ".github/workflows/lint.yml"
  push:
    branches: [main]
    paths:
      - "**/*.py"
      - "**/*.rs"
      - "pyproject.toml"
      - "Cargo.toml"
      - ".pre-commit-config.yaml"
      - ".github/workflows/lint.yml"
  workflow_dispatch:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - uses: astral-sh/setup-uv@v9.0.0
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: uv sync --group dev
        # https://github.com/pre-commit/action/blob/main/action.yml doesn't work because it uses the wrong python lol
      - run: uv run pre-commit run --all-files --show-diff-on-failure --color=always --hook-stage pre-push
